# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4250ea86cf40aaed27411319bd778e94c9a237c581b78a36471f4c47f3918e5fec113402de11c76aa6d0be92e14e6ff2b5c24f9bab94662261f0ebe5beb1b6d0

test:
  secret_key_base: 2b484d1a09b3e0110ea43807deeadb4f3c28e22de5049e0a881aeb177efb6a23b6ae457e5cc0324a705a3fa5ee2dbcdc82c4132188c4f1e1d8af4d489ee81b5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
